/**
 * Maintenance-only source erasure lifecycle.
 *
 * A restored source is intentionally not made readable again: restoration
 * only releases the external identity for a fresh ingestion with a new source
 * id. This keeps erased material out of every read model and replay payload.
 */
import { contextPartitionKeySchema } from "./partition.js";
import { z } from "zod";
import { typeIdSchema } from "~/types/typeid.js";

export const sourceLifecycleActionSchema = z.enum([
  "tombstone",
  "restore",
  "purge",
]);
export type SourceLifecycleAction = z.infer<typeof sourceLifecycleActionSchema>;

export const sourceLifecycleStateSchema = z.enum([
  "tombstoned",
  "restored",
  "purged",
]);
export type SourceLifecycleState = z.infer<typeof sourceLifecycleStateSchema>;

export const sourceStorageCleanupStateSchema = z.enum([
  "not_required",
  "pending",
  "completed",
]);
export type SourceStorageCleanupState = z.infer<
  typeof sourceStorageCleanupStateSchema
>;

export const sourceLifecycleCommandRequestSchema = z.object({
  userId: z.string().min(1),
  sourceId: typeIdSchema("source"),
  expectedPartitionKey: contextPartitionKeySchema.nullable(),
  expectedSourceVersion: z.number().int().nonnegative(),
  /** Durable caller-owned idempotency key. Retries reuse it verbatim. */
  /** Opaque UUID generated by the maintenance caller; never a user label. */
  commandId: z.string().uuid(),
  action: sourceLifecycleActionSchema,
});
export type SourceLifecycleCommandRequest = z.infer<
  typeof sourceLifecycleCommandRequestSchema
>;

export const sourceLifecycleCommandResponseSchema = z.object({
  sourceId: typeIdSchema("source"),
  commandId: z.string().uuid(),
  action: sourceLifecycleActionSchema,
  state: sourceLifecycleStateSchema,
  replayed: z.boolean(),
  /** A restore never revives erased bytes or prior graph evidence. */
  freshIngestionRequired: z.boolean(),
  storageCleanupState: sourceStorageCleanupStateSchema,
  sourceVersion: z.number().int().nonnegative().nullable(),
  restorableUntil: z.coerce.date().nullable(),
});
export type SourceLifecycleCommandResponse = z.infer<
  typeof sourceLifecycleCommandResponseSchema
>;

/** Bounded maintenance retry for opaque physical-object cleanup receipts. */
export const sourceLifecycleStorageCleanupSweepRequestSchema = z.object({
  limit: z.number().int().positive().max(1_000).default(100),
});
export type SourceLifecycleStorageCleanupSweepRequest = z.input<
  typeof sourceLifecycleStorageCleanupSweepRequestSchema
>;

/** Non-content progress only; individual source identities are never exposed. */
export const sourceLifecycleStorageCleanupSweepResponseSchema = z.object({
  attempted: z.number().int().nonnegative(),
  completed: z.number().int().nonnegative(),
});
export type SourceLifecycleStorageCleanupSweepResponse = z.infer<
  typeof sourceLifecycleStorageCleanupSweepResponseSchema
>;

/** Bounded maintenance recovery for migrated soft-deleted source evidence. */
export const sourceLifecycleReadModelRetractionSweepRequestSchema = z.object({
  limit: z.number().int().positive().max(1_000).default(100),
});
export type SourceLifecycleReadModelRetractionSweepRequest = z.input<
  typeof sourceLifecycleReadModelRetractionSweepRequestSchema
>;

/** Aggregate-only result; never leaks source identity or erased content. */
export const sourceLifecycleReadModelRetractionSweepResponseSchema = z.object({
  attempted: z.number().int().nonnegative(),
  completed: z.number().int().nonnegative(),
});
export type SourceLifecycleReadModelRetractionSweepResponse = z.infer<
  typeof sourceLifecycleReadModelRetractionSweepResponseSchema
>;
